CREATE TABLE `TEST` (
	`ID` SERIAL,
	`STUDENT_NO` VARCHAR(10) NOT NULL,
	`SUBJECT_CD` CHAR(3) NOT NULL,
	`SCHOOL_CD` CHAR(10) NOT NULL,
	`NO` INT(10) NOT NULL,
	`POINT` INT(10) DEFAULT NULL,
	`CLASS_NUM` VARCHAR(5) DEFAULT NULL,
	PRIMARY KEY (`STUDENT_NO`,`SUBJECT_CD`,`SCHOOL_CD`,`NO`)
) ENGINE=InnoDB;